#cat << EOF > environments/demo-env/dataplane/patch-nodeset-nodes.yaml
  - op: add
    path: /spec/nodes/edpm-compute-1
    value:
      hostName: edpm-compute-1
      networks:
      - name: ctlplane
        subnetName: subnet1
        defaultRoute: false
        fixedIP: 172.22.0.100
      - name: internalapi
        subnetName: subnet1
        fixedIP: 172.17.0.100
      - name: storage
        subnetName: subnet1
        fixedIP: 172.18.0.100
      - name: tenant
        subnetName: subnet1
        fixedIP: 172.19.0.100
      - name: external
        subnetName: subnet1
        fixedIP: 172.21.0.100
      ansible:
        ansibleHost: 172.22.0.100
        ansibleUser: dem
        ansibleVars:
          fqdn_internal_api: compute01.ocp4.ocp.lan
#EOF