apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - https://github.com/openstack-gitops/rhoso-gitops/base/initialize/gitops/components/annotations?ref=main

resources:
  - https://github.com/cotcaru-org/openstack_on_ocp/content/files/manifests/base/controlplane/?ref=main