apiVersion: network.openstack.org/v1beta1
kind: NetConfig
metadata:
  name: openstacknetconfig
  namespace: openstack
spec:
  networks:
  - name: ctlplane
    dnsDomain: ctlplane.openstack.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.22.0.120
        start: 172.22.0.100
      - end: 172.22.0.200
        start: 172.22.0.150
      cidr: 172.22.0.0/24
      gateway: 172.22.0.1
  - name: internalapi
    dnsDomain: internalapi.openstack.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.17.0.250
        start: 172.17.0.100
      excludeAddresses:
      - 172.17.0.10
      - 172.17.0.12
      cidr: 172.17.0.0/24
  - name: tenant
    dnsDomain: tenant.openstack.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.19.0.250
        start: 172.19.0.100
      excludeAddresses:
      - 172.19.0.10
      - 172.19.0.12
      cidr: 172.19.0.0/24
  - name: storage
    dnsDomain: storage.openstack.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 192.168.1.241
        start: 192.168.1.239
      excludeAddresses:
      - 192.168.1.230
      - 192.168.1.232
      cidr: 192.168.1.0/24
  - name: external
    dnsDomain: external.openstack.svc.cluster.local
    subnets:
    - name: subnet1
      allocationRanges:
      - end: 172.21.0.250
        start: 172.21.0.100
      excludeAddresses:
      - 172.21.0.10
      - 172.21.0.11
      - 172.21.0.12
      cidr: 172.21.0.0/24